const dasha = require("@dasha.ai/sdk");

// This code was generated by Dasha Playground.
// See README.md to start
const message = () => {
	alert("hello");
}


const main = async () => {
	const app = await dasha.deploy("./app");
	await app.start({ concurrency: 10 });

	const sandbox = {
		tts: "dasha",
		stt: "default",
		endpoint:  "918588922986",
		execute: async (input) => {
			const conv = app.createConversation(input);
			const channel = sandbox.endpoint !== "chat" ? "audio" : "text";

			if (channel === "audio") {
				conv.on("transcription", (log) => console.log(log));
			}

			if (channel === "text") {
				await dasha.chat.createConsoleChat(conv);
			}

			conv.audio.tts = sandbox.tts;
			conv.audio.stt = sandbox.stt;
			conv.audio.noiseVolume = 0;

			return await conv.execute({ channel });
		},
	};

	app.setExternal("someExternalFunction", (output) => {
	  console.log(output)
	});
	
	const output = await sandbox.execute({ 
	  endpoint: sandbox.endpoint,
	  name: "Ashwin",
	});
	
	console.log(output);
}

main();

